---

- name: assert all vars are set
  assert: 
    that: "{{ item }} != '' "
  with_items:
    - required_space_mb

- shell: df -Hm /Applications | tail -n 1 | awk {'print $4 '} 
  register: test

- set_fact: 
    free_space_mb: "{{ test.stdout }}"

- name: validate required
  assert:
    that:
      - free_space_mb|int > required_space_mb|int
    fail_msg: "free space test failed: {{ free_space_mb }} < {{ required_space_mb }}"
    success_msg: free space test passed
